# Site
favicon: images/favicon.png

# Personal info
name: Анастасия Скрипникова
title: Junior QA Engineer
email: skripnikovanastia@gmail.com
phone: +7(921)100-77-28
#website: 

# Social links
vk_username: skr.nastia
telegram_username: nulevaya

# About Section
about_title: Обо мне
about_profile_image: images/profile.jpg
about_content: | 
  Увлекаюсь IT и программированием, имею представление, каково это - много учиться и работать, чтобы достичь результата. 
  Не боюсь трудностей и готова к новому опыту.

  Навыки и инструменты:
    - Ручное тестирование
    - PostgreSQL/SQLite3
    - HTML, CSS, JavaScript
    - Git
    - Jira/Яндекс.Трекер
    - rspec
    - Charles
    - Postman
    - Browser devtools
    - Unix (MacOS)
    - Ruby (Rails, Sinatra + Bootstrap, Hanami)

# Projects Section
projects_title: Чему обучалась

# Experience Section
experience_title: Опыт

# Education Section
education_title: Образование

# More Section
more_title: Немного больше обо мне
more_content: |
  Считаю своими плюсами упорство и усидчивость. Увлечениям, изучению новых навыков и работе 
  посвящаю максимум своего времени, быстро втягиваясь в новую для меня сферу. <br>

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]