# Site
favicon: images/favicon.png

# Personal info
name: Анастасия Скрипникова
title: Junior Ruby on Rails Developer
email: skripnikovanastia@gmail.com
phone: +7(921)100-77-28
#website: 

# Social links
github_username:  nulevaya
vk_username: skr.nastia

# About Section
about_title: Обо мне
about_profile_image: images/profile.jpg
about_content: | 
  Увлекаюсь IT и программированием, имею представление, какового это - много учиться и работать, чтобы достичь результата. 
  Не боюсь трудностей и готова к новому опыту.

  С чем работала:
    - Unix(MacOS)
    - Git
    - Ruby
    - Rails
    - Sinatra
    - Bootstrap
    - SQLite3/PostgreSQL
    - Jira/Startrek

  С чем знакома: 
    - HTML, CSS, Javascript
    - Docker
    - C/C++
    - C#

# Projects Section
projects_title: Чему обучалась

# Experience Section
experience_title: Опыт

# Education Section
education_title: Образование

# More Section
more_title: Немного больше обо мне
more_content: |
  Еще со школы я представляла программирование как самую потрясающую в мире работу. Что может быть лучше, чем заниматься
  любимым делом, непрерывно познавать что-то новое и интересное, ещё и получать за это деньги?<br>
  <br>
  Прошла объемный курс по Ruby on Rails, сделала несколько учебных проектов (Ruby on Sinatra + Bootstrap, Ruby on Rails,
  Ruby on Rails + Bootstrap), что открыло для меня большой и интересный мир бэкенда. Закончила курс по SQL запросам, 
  не обошла стороной курс по верстке, чтобы иметь всестороннее представление о мире web-программирования.<br>
  Устроилась тестировщиком в Яндекс, чтобы на собственном опыте понять принципы тестирования и иметь коммерческий опыт работы с 
  большим коллективом в серьезной компании. <br>
  Благодаря хорошим людям, что встретились мне на жизненном пути, пусть неофициально, но решала задачи на 
  большом действующем проекте, что дало мне опыт работы в продакшене и представление о взаимодействии с большой 
  командной разработчиков.<br>
  <br>
  И вот сейчас, в 21 год, я понимаю, что готова пойти навстречу новому интересному опыту и 
  начать серьезно развиваться как программист. Я не хочу стоять на месте, я хочу двигаться вперед к заветной мечте через 
  любые трудности.<br>
  <br>
  Спасибо за внимание :)

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]